export * from './components/driver/driver.component';
export * from './components/fare/fare.component';
export * from './components/income/income.component';
export * from './components/notification/notification.component';
export * from './components/passenger/passenger.component';
export * from './components/profile/profile.component';
export * from './components/reports/reports.component';
export * from './components/time-and-distance/time-and-distance.component';
export * from './components/trip/trip.component';
export * from './components/wallet/wallet.component';
export * from './components/trip/index'
export * from './components/comments/comments.component'
export * from './components/payment/payment.component'
export * from './components/places/places.component';
export * from './components/partners/partners.component';